### screen
GET {{host}}/api/v1/screens/{{screenId}}


### BOOK
POST {{host}}/api/v1/books
Content-Type: application/json

{
  "userId": 1,
  "screenId": 1,
  "seats": [
    {
      "row": 0,
      "col": 1,
      "type": "FRONT"
    }
  ]
}


### PAY
POST {{host}}/api/v1/payments
Content-Type: application/json

{
  "userId": 1,
  "bookId": 1
}


### get post
#GET {{host}}/api/v1/posts/{{postId}}


