### bookable seats
GET {{host}}/api/v1/screens/{{screenId}}/seats


### screens
GET {{host}}/api/v1/screens/movies/{{movieId}}?date=2021-09-25 01:00:00


### pass LocalDateTime to requestParam
GET {{host}}/test2?date=2021-09-04 01:00:00