spring:
  h2:
    console:
      enabled: true
      path: /h2

## 개발 환경은 H2를 사용
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 30
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: ALWAYS

logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "error"
