server:
  port: 8082

spring:
  h2:
    console:
      enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234!@#$
    url: jdbc:mysql://ip-172-31-7-9.ap-northeast-2.compute.internal/testdb?serverTimezone=UTC

  ### JPA 설정 오버라이딩 ###
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

sentry:
  dsn: https://924d78ead05f4630a3ab88904a2d60e4@o1034575.ingest.sentry.io/6003049
  traces-sample-rate: 1.0