server:
  port: 8080

spring:
  h2:
    console:
      enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234!@#$
    url: jdbc:mysql://10.178.0.23/testdb?serverTimezone=UTC

  ### JPA 설정 오버라이딩 ###
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

sentry:
  dsn: https://163b2d7b7ce3463491dbd400cf8605cc@o1035787.ingest.sentry.io/6003077
  traces-sample-rate: 1.0

logging:
  level:
    root: "warn"
    org.springframework.web: "warn"
    org.hibernate: "error"